In [9]:
#dahyun의 가방 안에서 '다이아몬드'를 훔쳐볼까요?
dahyun = ['은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '다이아몬드', '은']

#이 가방에 한번 넣어봅시다!
stealBag1 = dahyun[-2]

#tzuyu는 가방 안 깊숙히 금을 13개 가지고 있네요! 이것들도 한번 훔쳐볼까요?
tzuyu = ['은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은', '은','금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금' ]

#이 가방에 한번 넣어봅시다!
stealBag2 = tzuyu[-13:]

#여러분이 훔쳐온 보석은 무엇인지 print()를 이용해서 한번 확인해보세요!
print('dahyun로부터 훔쳐온 보석은', stealBag1)
print('tzuyu로부터 훔쳐온 보석은', stealBag2)

dahyun로부터 훔쳐온 보석은 다이아몬드
tzuyu로부터 훔쳐온 보석은 ['금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금', '금']


In [42]:
a = ['ring']
b = ['ding']
c = ['dong']
d = ['diggi']

# 연결 연산자를 이용해서 ['ring', 'ding', 'dong']를 lyric에 대입해봅시다.
lyric = a + b + c
print(lyric)

# 수능을 하루 앞둔 친구에게 수능 금지곡을 들려줍시다!
# 변수 shinee에 다음 리스트를 담아봅시다.
# ['ring', 'ding', 'dong', 'ring', 'ding', 'dong']

shinee1 = lyric + lyric
print(shinee1)

# 노래가 좀 짧네요! 뒷부분도 불러봅시다!
#['ring','diggi','ding','diggi','ding','ding','ding']

shinee2 = a + d + b + d + 3 * b
print(shinee1, shinee2)

['ring', 'ding', 'dong']
['ring', 'ding', 'dong', 'ring', 'ding', 'dong']
['ring', 'ding', 'dong', 'ring', 'ding', 'dong'] ['ring', 'diggi', 'ding', 'diggi', 'ding', 'ding', 'ding']


In [41]:
sum = 0
for i in [1, 2, 3]:
    sum += i
print(sum)

6


In [44]:
mix = "쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰쌀씰쌀쌀씰쌀씰"
count= 0

for i in mix:
    if i == "쌀":
        count += 1
    else:
        pass

print(count)

300


In [47]:
#for-range()를 이용해서 19단을 전부 출력해봅시다!
for i in range(1,20):
    print(i, "단 :", end="")
    for j in range(1, 20):
        result = i * j
        print(result, end=", ")
    print()

1 단 :1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
2 단 :2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 
3 단 :3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 
4 단 :4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 
5 단 :5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 
6 단 :6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96, 102, 108, 114, 
7 단 :7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 
8 단 :8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 
9 단 :9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171, 
10 단 :10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 
11 단 :11, 22, 33, 44, 55, 66, 77, 88, 99, 110, 121, 132, 143, 154, 165, 176, 187, 198, 209, 
12 단 :12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192

In [32]:
import numpy as np
def main():
    print("1차원 array")
    array = np.arange(10)
    print(array)

    # Q1. array의 자료형을 출력해보세요.
    print("Q1 :", type(array))

    # Q2. array의 차원을 출력해보세요.
    print("Q2 :", array.ndim)

    # Q3. array의 모양을 출력해보세요.
    print("Q3 :", array.shape)
    
    # Q4. array의 크기를 출력해보세요.
    print("Q4 :", array.size)
    
    # Q5. array의 dtype(data type)을 출력해보세요.
    print("Q5 :", array.dtype)
    
    # Q6. array의 5번째 요소를 출력해보세요.
    print("Q6 :", array[4])
    
    # Q7. array의 4번째 요소부터 5번째 요소까지 출력해보세요.
    print("Q7 :", array[3:5])

    
if __name__ == "__main__":
    main()

1차원 array
[0 1 2 3 4 5 6 7 8 9]
Q1 : <class 'numpy.ndarray'>
Q2 : 1
Q3 : (10,)
Q4 : 10
Q5 : int64
Q6 : 4
Q7 : [3 4]


In [40]:
def main():
    array = np.array([1,2,3,4,5])
    
    print(array)
    
    # Q1. array에 5를 더한 값을 출력해보세요.
    print("array + 5 : ", array + 5)
    
    # Q2. array에 5를 뺀 값을 출력해보세요.
    print("array - 5 : ", array - 5)
    
    # Q3. array에 5를 곱한 값을 출력해보세요.
    print("array * 5 : ", array * 5)
    
    # Q4. array를 5로 나눈 값을 출력해보세요.
    print("array / 5 : ", array / 5)
    
    
    # Q5. array에 array2를 더한 값을 출력해보세요.    
    array2 = np.array([5,4,3,2,1])
    
    print("배열끼리의 덧셈 : ", array + array2)
    
    # Q6. array에 array2를 뺀 값을 출력해보세요.
    print("배열끼리의 뺄셈 : ", array - array2)
    
if __name__ == "__main__":
    main()

[1 2 3 4 5]
array + 5 :  [ 6  7  8  9 10]
array - 5 :  [-4 -3 -2 -1  0]
array * 5 :  [ 5 10 15 20 25]
array / 5 :  [0.2 0.4 0.6 0.8 1. ]
배열끼리의 덧셈 :  [6 6 6 6 6]
배열끼리의 뺄셈 :  [-4 -2  0  2  4]


In [48]:
x = np.arange(8).reshape(2, 4)
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
np.sum(x)

28

In [50]:
np.max(x)

7

In [51]:
np.min(x)

0

In [52]:
np.mean(x)

3.5

In [53]:
np.median(x)

3.5

In [55]:
np.mean(x, axis=0)

array([2., 3., 4., 5.])

In [56]:
np.mean(x, axis=1)

array([1.5, 5.5])

In [66]:
def main():
    matrix = np.arange(8).reshape(2, 4)
    print(matrix)

    print("Q1:", np.sum(matrix))
    print("Q2:", np.max(matrix))
    print("Q3:", np.min(matrix))
    print("Q4:", np.mean(matrix))
    print("Q5:", np.sum(matrix, axis=0))
    print("Q6:", np.sum(matrix, axis=1))
    print("Q7:", np.std(matrix))
    print("Q8:", matrix[matrix < 5])

if __name__ == "__main__":
    main()

[[0 1 2 3]
 [4 5 6 7]]
Q1: 28
Q2: 7
Q3: 0
Q4: 3.5
Q5: [ 4  6  8 10]
Q6: [ 6 22]
Q7: 2.29128784747792
Q8: [0 1 2 3 4]
