# Numpy

In [2]:
import numpy as np
# 대규모 다차원 배열을 다룰 수 있는 라이브러리 : numpy

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [5]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.ones((3, 3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.random.random((2, 2))

array([[0.90029495, 0.05438639],
       [0.52983207, 0.82948837]])

In [12]:
np.random.normal(0, 1, (2, 2))

array([[ 0.37355241, -1.29496241],
       [-0.36268713,  1.51788663]])

In [19]:
x1 = np.random.randint(0, 10, (5, 5))
x1

array([[1, 5, 9, 2, 6],
       [1, 7, 8, 8, 5],
       [8, 8, 4, 5, 8],
       [8, 6, 5, 3, 9],
       [6, 7, 9, 4, 4]])

In [20]:
x1.shape

(5, 5)

In [25]:
# Indexing
x1[-1, -1]

4

In [24]:
# Slicing
x1[0:3, 2:4]

array([[9, 2],
       [8, 8],
       [4, 5]])

# Pandas

In [26]:
import pandas as pd
# pandas : 구조화된 데이터를 효과적으로 처리하고 저장

In [50]:
country = pd.read_csv("country.csv")
country

menu    gdp   pop   cap
0  china  10000     1     1
1  korea  20000     2     2
2  japan  30000     3     3
3    usa  40000     4     4

In [34]:
country = pd.read_csv("country.csv", index_col="menu")
country

gdp   pop   cap
menu                    
china  10000     1     1
korea  20000     2     2
japan  30000     3     3
usa    40000     4     4

In [38]:
country.iloc[0]

 gdp    10000
 pop        1
 cap        1
Name: china, dtype: int64

In [39]:
country.iloc[:2, 0]

menu
china    10000
korea    20000
Name:  gdp, dtype: int64

In [42]:
# 누락된 데이터
country.isnull()

gdp    pop    cap
menu                      
china  False  False  False
korea  False  False  False
japan  False  False  False
usa    False  False  False

# matplotlib

In [46]:
import matplotlib.pyplot as plt
import seaborn as sns
# 파이썬에서 데이터를 그래프타 차트로 시각화 할 수 있는 라이브러리